### PR TITLE
Fixes #16: Add flag to enable use of full instance name as the machine name

### LINKED ISSUE #16: Dropping the first part of the instance name creates issue in the inventory
Hi!

What's the reason behind dropping the first part of the instance name when generating the machine name?

```
      def machine_name
        return @machine_name if defined? @machine_name
        @machine_name = instance.name.gsub(/[<>]/, '').split("-").drop(1).join("-")
        debug("machine_name=" + @machine_name.to_s)
        @machine_name
      end
```

I have an issue with the incomplete machine name when I try to use the inventory (it just ignores the test suite)
Plus: the way of dropping the first part fails if the suite itself has a dash in it.

```
> ./test.sh converge default-debian-7
-----> Starting Kitchen (v1.7.2)
-----> Creating <default-debian-7>...
       Digital Ocean instance <13216593> created.
       Waiting for SSH service on 45.55.201.154:22, retrying in 3 seconds
       Waiting for SSH service on 45.55.201.154:22, retrying in 3 seconds
       [SSH] Established
       (ssh ready)

       Finished creating <default-debian-7> (0m36.71s).
-----> Converging <default-debian-7>...
$$$$$$ Running legacy converge for 'Digitalocean' Driver
       Preparing files for transfer
       *************** AnsiblePush install_command ***************
       Ansible push config validated
       Transferring files to <default-debian-7>
       *************** AnsiblePush run ***************

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [debian-7]

TASK [apt_preferences : Remove APT preferences] ********************************

TASK [apt_preferences : Create APT preferences] ********************************

PLAY RECAP *********************************************************************
debian-7                   : ok=1    changed=0    unreachable=0    failed=0

       *************** idempotency test ***************
Using changes callback for V2

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [debian-7]

TASK [apt_preferences : Remove APT preferences] ********************************

TASK [apt_preferences : Create APT preferences] ********************************

PLAY RECAP *********************************************************************
debian-7                   : ok=1    changed=0    unreachable=0    failed=0

       idempotency test [passed]
       *************** AnsiblePush end run *******************
       Finished converging <default-debian-7> (0m9.29s).
-----> Kitchen is finished. (0m46.30s)
```

Check out the generated inventory below:

```
> kitchen-ansible-inventory
{
  "all": [
    "debian-7"
  ],
  "_meta": {
    "hostvars": {
      "debian-7": {
        "ansible_ssh_host": "45.55.201.154",
        "ansible_ssh_port": "22",
        "ansible_ssh_private_key_file": "/Users/asalvo/.ssh/id_rsa"
      }
    }
  }
}
```

Any reason for not using the complete instance name?
I think just removing `.split("-").drop(1).join("-")` would be enough.

What do you think?

Regards!
    --Ariel

### PR DESCRIPTION
**Pull request by athak**
This PR adds the use_instance_name flag.

The flag is set to false by default which sets the machine name to the platform name (the originally intended behavior). If set to true, the machine name is set to the instance name (suite+platform)

### CODE REVIEW

File: lib/kitchen/provisioner/ansible_push.rb [hunk 1]
```diff
@@ -88,7 +89,11 @@ def conf
 
       def machine_name
         return @machine_name if defined? @machine_name
-        @machine_name = instance.name.gsub(/[<>]/, '').split("-").drop(1).join("-")
+        unless config[:use_instance_name]
+          @machine_name = instance.platform.name.gsub(/[<>]/, '')
```
Comment (ahelal) [inline lib/kitchen/provisioner/ansible_push.rb]: I think using platform name might be an issue. As it translates **-** to **_** for example. While probably its safer than using 

``` ruby
instance.name.gsub(/[<>]/, '').split("-").drop(1).join("-")
```

But that would be breaking changes a version upgrade might be required.  Another aproach would be just to use the old function and in the next breaking change would include that your suggestion ?

Whats your thoughts ?

Comment (athak) [inline lib/kitchen/provisioner/ansible_push.rb]: From our previous discussion on the issue, I thought this was on the spirit of your original intention. But you're right, if it is considered a breaking change we can leave the previous implementation and push this on 0.4. Let me know and I'll update the PR.

Comment (ahelal) [inline lib/kitchen/provisioner/ansible_push.rb]: then 0.4.0 it is 👍

Comment (athak) [inline lib/kitchen/provisioner/ansible_push.rb]: Done, PR is updated :)
